export const COLLECTION_MINTED_INITIAL_LENGTH = 6;
export const COLLECTION_MINTED_RESPONSE_LIMIT = 6;
export const COLLECTION_ACTIVITY_INITIAL_LENGTH = 8;
export const COLLECTION_ACTIVITY_RESPONSE_LIMIT = 8;
export const COLLECTION_MOMENT_INITIAL_LENGTH = 6;
export const COLLECTION_MOMENT_RESPONSE_LIMIT = 6;
